apiVersion: apps/v1
kind : Deployment
metadata:
     name: color-app
     labels:
         app: color-app
spec:
     replicas: 1
     selector:
         matchLabels:
             app: color-app
     template:
         metadata:
             labels:
                app: color-app
         spec:
             containers:
             -  name: color-app
                image: skycolor.azurecr.io/skycolor
                ports:
                -  containerPort: 80
                
---
apiVersion: v1
kind: Service    
metadata:
     name: color-app-service
spec:
     selector:
       app: color-app
     type: LoadBalancer 
     ports:
       - protocol: TCP
         port: 80
         targetPort: 80   
           
          
